import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {SessionProvider} from "next-auth/react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SessionProvider 
          // 5分（300秒）ごとにバックエンドにセッションを確認しに行く
          // セッションが切れていれば、自動的に status が "unauthenticated" になる
          refetchInterval={10 * 60} 
          // ウィンドウをフォーカスしたときにもチェックする（推奨）
          refetchOnWindowFocus={true}
        >
        {children}
        </SessionProvider>
      </body>
    </html>
    
  );
}
